/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseFormDropFile: typeof import('./src/components/Base/Form/DropFile.vue')['default']
    BaseModal: typeof import('./src/components/Base/Modal/Modal.vue')['default']
    BaseModalBackdrop: typeof import('./src/components/Base/Modal/ModalBackdrop.vue')['default']
    BaseSprite: typeof import('./src/components/Base/Sprite.vue')['default']
    BattleBox: typeof import('./src/components/BattleBox.vue')['default']
    PlayerAvatar: typeof import('./src/components/PlayerAvatar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
